Traceback (most recent call last):
  File "/zhome/a1/4/145993/courses/special course/Special-Course/src/train.py", line 189, in <module>
    train()
    ~~~~~^^
  File "/zhome/a1/4/145993/courses/special course/Special-Course/src/train.py", line 31, in train
    dataset = ArcticDataloader(
        bedmachine_path=os.path.join("data", "Bedmachine", "BedMachineGreenland-v5.nc"),
    ...<2 lines>...
        snow_accumulation_path="data/Snow_acc/...",
    )
  File "/zhome/a1/4/145993/courses/special course/Special-Course/data/data_preprocessing.py", line 34, in __init__
    tar.extractall(path=extracted_path, filter="fully_trusted")
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/appl9/python/3.13.0/lib/python3.13/tarfile.py", line 2334, in extractall
    self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      numeric_owner=numeric_owner)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/appl9/python/3.13.0/lib/python3.13/tarfile.py", line 2397, in _extract_one
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                         set_attrs=set_attrs,
                         ^^^^^^^^^^^^^^^^^^^^
                         numeric_owner=numeric_owner)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/appl9/python/3.13.0/lib/python3.13/tarfile.py", line 2480, in _extract_member
    self.makefile(tarinfo, targetpath)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/appl9/python/3.13.0/lib/python3.13/tarfile.py", line 2534, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/appl9/python/3.13.0/lib/python3.13/tarfile.py", line 250, in copyfileobj
    buf = src.read(bufsize)
KeyboardInterrupt
